version: "3"
services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data/metabase:/metabase-data
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres

  caddy:
    image: abiosoft/caddy:${DOCKER_TAG_CADDY}
    depends_on:
      - metabase
    ports:
      - ${EXTERNAL_2015_PORT}:2015
      - ${EXTERNAL_443_PORT}:443
      - ${EXTERNAL_80_PORT}:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./data/caddy:/root/.caddy
    env_file:
      - .env
    restart: always
